name: Format Code

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run prettier
        run: creyD/prettier_action@v4.3
        with:
          commit_message: "chore: run prettier"
