services:
  frontend:
    build:
      context: "./frontend"
      dockerfile: "./Dockerfile"
    ports:
      - "4200:4200"
    networks:
      - events_net
  backend:
    build:
      context: "./backend"
      dockerfile: "./Dockerfile"
    ports:
      - "3000:3000"
    networks:
      - events_net

networks:
  events_net: